version: '3.8'

services:
  db:
    image: postgres:17
    container_name: homeflip_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homeflip_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/01_init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./seeds/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql

volumes:
  postgres_data:
